CREATE TABLE countries (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(10) NOT NULL,
    flag_emoji VARCHAR(10)
);

INSERT INTO countries (name, code, flag_emoji) VALUES
('Sri Lanka','LK','🇱🇰'),
('India','IN','🇮🇳'),
('Thailand','TH','🇹🇭'),
('United Kingdom','GB','🇬🇧'),
('Philippines','PH','🇵🇭'),
('United States','US','🇺🇸'),
('Canada','CA','🇨🇦'),
('China','CN','🇨🇳'),
('Hong Kong','HK','🇭🇰'),
('United Arab Emirates','AE','🇦🇪'),
('Malaysia','MY','🇲🇾'),
('Kenya','KE','🇰🇪'),
('Nepal','NP','🇳🇵'),
('Congo','CG','🇨🇬'),
('Ghana','GH','🇬🇭'),
('Nigeria','NG','🇳🇬'),
('Estonia','EE','🇪🇪'),
('France','FR','🇫🇷'),
('Belgium','BE','🇧🇪'),
('Bangladesh','BD','🇧🇩'),
('Pakistan','PK','🇵🇰'),
('Afghanistan','AF','🇦🇫'),
('Greece','GR','🇬🇷'),
('Qatar','QA','🇶🇦'),
('Australia','AU','🇦🇺'),
('Åland Islands','AX','🇦🇽'),
('Andorra','AD','🇦🇩'),
('Austria','AT','🇦🇹'),
('Azores','PT','🇵🇹'),
('Bulgaria','BG','🇧🇬'),
('Canary Islands','ES','🇪🇸'),
('Croatia','HR','🇭🇷'),
('Cyprus','CY','🇨🇾'),
('Czech Republic','CZ','🇨🇿'),
('Denmark','DK','🇩🇰'),
('Finland','FI','🇫🇮'),
('French Guiana','GF','🇬🇫'),
('Germany','DE','🇩🇪'),
('Gibraltar','GI','🇬🇮'),
('Guadeloupe','GP','🇬🇵'),
('Guernsey','GG','🇬🇬'),
('Hungary','HU','🇭🇺'),
('Iceland','IS','🇮🇸'),
('Ireland','IE','🇮🇪'),
('Isle of Man','IM','🇮🇲'),
('Italy','IT','🇮🇹'),
('Jersey','JE','🇯🇪'),
('Latvia','LV','🇱🇻'),
('Liechtenstein','LI','🇱🇮'),
('Lithuania','LT','🇱🇹'),
('Luxembourg','LU','🇱🇺'),
('Madeira','PT','🇵🇹'),
('Malta','MT','🇲🇹'),
('Martinique','MQ','🇲🇶'),
('Mayotte','YT','🇾🇹'),
('Monaco','MC','🇲🇨'),
('Netherlands','NL','🇳🇱'),
('Norway','NO','🇳🇴'),
('Poland','PL','🇵🇱'),
('Portugal','PT','🇵🇹'),
('Réunion','RE','🇷🇪'),
('Romania','RO','🇷🇴'),
('Saint Barthélemy','BL','🇧🇱'),
('Saint Martin','MF','🇲🇫'),
('Saint Pierre and Miquelon','PM','🇵🇲'),
('San Marino','SM','🇸🇲'),
('Slovakia','SK','🇸🇰'),
('Slovenia','SI','🇸🇮'),
('Spain','ES','🇪🇸'),
('Sweden','SE','🇸🇪'),
('Switzerland','CH','🇨🇭'),
('Vatican City State','VA','🇻🇦'),
('Singapore','SG','🇸🇬'),
('Bahrain','BH','🇧🇭'),
('Indonesia','ID','🇮🇩'),
('Israel','IL','🇮🇱'),
('Japan','JP','🇯🇵'),
('Kuwait','KW','🇰🇼'),
('Mexico','MX','🇲🇽'),
('New Zealand','NZ','🇳🇿'),
('Oman','OM','🇴🇲'),
('Saudi Arabia','SA','🇸🇦'),
('Turkey','TR','🇹🇷'),
('Uganda','UG','🇺🇬'),
('South Africa','ZA','🇿🇦'),
('Senegal','SN','🇸🇳'),
('Vietnam','VN','🇻🇳');
